import QueryProvider from '@/context/QueryProvider'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import AuthProvider from '@/context/AuthContext'

const figtree = Figtree({
	variable: '--font-figtree-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${figtree.variable} antialiased`}>
				<QueryProvider>
					<AuthProvider>{children}</AuthProvider>
				</QueryProvider>
				<Toaster
					toastOptions={{
						duration: 2000,
					}}
				/>
			</body>
		</html>
	)
}
